[phases.setup]
nixPkgs = ['python39', 'gcc']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['python init_railway_db.py']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT wsgi:app'