providers = ["python"]

[phases.setup]
nixPkgs = ["gcc", "pkg-config", "mysql80", "libmysqlclient", "zlib"]

[variables]
PYTHONPATH = "/app"

[phases.build]
cmds = [
  'mkdir -p logs proyecto/static/uploads',
  'python init_railway_db.py'
]

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 wsgi:app'