# Railway Nixpacks Configuration - Official Best Practices
providers = ['python']

[phases.setup]
nixPkgs = ['gcc', 'pkg-config', 'mysql80', 'libmysqlclient', 'zlib', 'openssl']
aptPkgs = ['default-libmysqlclient-dev', 'build-essential']

[phases.install]
cmds = ['pip install --no-cache-dir -r requirements.txt']

[phases.build]
cmds = [
  'mkdir -p logs proyecto/static/uploads',
  'python init_railway_db.py'
]

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 wsgi:app'

[variables]
PYTHONPATH = '/app'