[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip', 'gcc', 'pkg-config', 'mysql80', 'libmysqlclient']

[phases.install]
cmds = ['python -m pip install --no-cache-dir -r requirements.txt']

[phases.build]
cmds = [
  'mkdir -p logs proyecto/static/uploads',
  'python init_railway_db.py'
]

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 wsgi:app'