[providers]
python = "3.9"

[variables]
PYTHONPATH = "/app"

[phases.build]
cmds = [
  'mkdir -p logs proyecto/static/uploads',
  'python init_railway_db.py'
]

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 wsgi:app'